spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/xie_tm
    username: postgre
    password: Zl830013
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5